name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Добавляем явные права на запись

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      shell: bash
      run: |
        mkdir -p build
        if [ ! -f License.rtf ]; then
          echo "{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1049{\fonttbl{\f0\fnil\fcharset0 Calibri;}}\viewkind4\uc1\pard\f0\fs22 MIT License\par }" > License.rtf
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make libfmt-dev rpm

    - name: Configure project
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: |
        cmake --build build --config Release --parallel 4

    - name: Generate packages
      run: |
        cd build
        cpack -G "DEB;RPM" || echo "Package generation failed"
        mkdir -p packages
        cp *.deb *.rpm packages/ || true

    - name: Create source archives
      run: |
        mkdir -p build/packages
        git archive --format=zip -o build/packages/source-code.zip HEAD
        git archive --format=tar.gz -o build/packages/source-code.tar.gz HEAD

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        artifacts: "build/packages/*"
        token: ${{ secrets.GITHUB_TOKEN }}
